## 1) Create an array of $9$ evenly spaced numbers going from $0$ to $29$ (inclusive) and give it the variable name $r$. Find the square of each element of the array (as simply as possible). Find twice the value of each element of the array in two different ways: $(i)$ using addition and $(ii)$ using multiplication. Print out the array $r$ and each output requested above.

In [14]:
import numpy as np

r = np.linspace(0, 29, 9)

#Square of each element

sqr = r**2


#Twice the value of each element

#(i) Sum

sm = r + r


#(ii) Multiplication

mlt = 2*r


print(r)
print(sqr)
print(sm)
print(mlt)

[ 0.     3.625  7.25  10.875 14.5   18.125 21.75  25.375 29.   ]
[  0.        13.140625  52.5625   118.265625 210.25     328.515625
 473.0625   643.890625 841.      ]
[ 0.    7.25 14.5  21.75 29.   36.25 43.5  50.75 58.  ]
[ 0.    7.25 14.5  21.75 29.   36.25 43.5  50.75 58.  ]


## 2) Create the following arrays:

### a) an array of $100$ elements all equal to $e$, the base of the natural logarithm

### b) an array in 1-degree increments of all the angles in degrees from $0$ to $360$ degrees inclusive;

### c) an array in 1-degree increments of all the angles in radians from $0$ to $360$ degrees inclusive. Verify your answers by show- ing that $c-b*np.pi/180$ gives an array of zeros (or nearly ze-ros) where b and c are the arrays you created in parts (b) and (c);

### d) an array from $12$ to $17$, not including $17$, in $0.2$ increments;

### e) an array from $12$ to $17$,  including $17$, in $0.2$ increments;

In [17]:
import numpy as np

#(a)

e = np.ones(100)
ex = np.exp(1)*e

In [18]:
ex

array([2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183,
       2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183,
       2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183,
       2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183,
       2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183,
       2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183,
       2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183,
       2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183,
       2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183,
       2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183,
       2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183,
       2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183,
       2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183,
       2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183,
       2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828

In [35]:
#(b)

b = np.arange(0, 361, 1)
b

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [36]:
#(c)

c = np.radians(b)
c

array([0.        , 0.01745329, 0.03490659, 0.05235988, 0.06981317,
       0.08726646, 0.10471976, 0.12217305, 0.13962634, 0.15707963,
       0.17453293, 0.19198622, 0.20943951, 0.2268928 , 0.2443461 ,
       0.26179939, 0.27925268, 0.29670597, 0.31415927, 0.33161256,
       0.34906585, 0.36651914, 0.38397244, 0.40142573, 0.41887902,
       0.43633231, 0.45378561, 0.4712389 , 0.48869219, 0.50614548,
       0.52359878, 0.54105207, 0.55850536, 0.57595865, 0.59341195,
       0.61086524, 0.62831853, 0.64577182, 0.66322512, 0.68067841,
       0.6981317 , 0.71558499, 0.73303829, 0.75049158, 0.76794487,
       0.78539816, 0.80285146, 0.82030475, 0.83775804, 0.85521133,
       0.87266463, 0.89011792, 0.90757121, 0.9250245 , 0.9424778 ,
       0.95993109, 0.97738438, 0.99483767, 1.01229097, 1.02974426,
       1.04719755, 1.06465084, 1.08210414, 1.09955743, 1.11701072,
       1.13446401, 1.15191731, 1.1693706 , 1.18682389, 1.20427718,
       1.22173048, 1.23918377, 1.25663706, 1.27409035, 1.29154

In [38]:
c_2 = c-b*(np.pi/180)
c_2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [39]:
#(d)

np.arange(12., 17., 0.2)

array([12. , 12.2, 12.4, 12.6, 12.8, 13. , 13.2, 13.4, 13.6, 13.8, 14. ,
       14.2, 14.4, 14.6, 14.8, 15. , 15.2, 15.4, 15.6, 15.8, 16. , 16.2,
       16.4, 16.6, 16.8])

In [40]:
#(e)
np.arange(12., 17.2, 0.2)

array([12. , 12.2, 12.4, 12.6, 12.8, 13. , 13.2, 13.4, 13.6, 13.8, 14. ,
       14.2, 14.4, 14.6, 14.8, 15. , 15.2, 15.4, 15.6, 15.8, 16. , 16.2,
       16.4, 16.6, 16.8, 17. ])

## 3) The position of a ball at time $t$ dropped with zero initial velocity from a height $h_{0}$ is given by

\begin{equation}
y = h_{0} - \frac{1}{2}gt^{2}
\end{equation}

## where $g = 9.8 m/s^{2}$. Suppose $h_{0} = 10m$. Find the sequence of times when the ball passes each half meter assuming the ball is dropped at $t = 0$. Hint: Create a NumPy array for $y$ that goes from $10$ to $0$ in increments of $−0.5$ using the arange function. Solving the above equation for $t$, show that

\begin{equation}
t = \sqrt{\frac{2(h_{0}-y)}{g}}
\end{equation}

## Using this equation and the array you created, find the sequence of times when the ball passes each half meter. Save your code as a Python script. It should yield the following results for the $y$ and $t$ arrays:

In [42]:
import numpy as np

h_0 = 10
y = np.arange(10., 0., -0.5)
y

array([10. ,  9.5,  9. ,  8.5,  8. ,  7.5,  7. ,  6.5,  6. ,  5.5,  5. ,
        4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5])

In [46]:
t = np.sqrt((2*(10 - y))/(9.8))
t

array([0.        , 0.31943828, 0.45175395, 0.55328334, 0.63887656,
       0.71428571, 0.7824608 , 0.84515425, 0.9035079 , 0.95831485,
       1.01015254, 1.05945693, 1.10656667, 1.15175111, 1.19522861,
       1.23717915, 1.27775313, 1.31707778, 1.35526185, 1.39239919])

In [47]:
list(zip(t,y))

[(0.0, 10.0),
 (0.3194382824999699, 9.5),
 (0.4517539514526256, 9.0),
 (0.5532833351724881, 8.5),
 (0.6388765649999398, 8.0),
 (0.7142857142857143, 7.5),
 (0.7824607964359516, 7.0),
 (0.8451542547285166, 6.5),
 (0.9035079029052512, 6.0),
 (0.9583148474999098, 5.5),
 (1.0101525445522108, 5.0),
 (1.0594569267279519, 4.5),
 (1.1065666703449761, 4.0),
 (1.1517511068997928, 3.5),
 (1.1952286093343936, 3.0),
 (1.2371791482634837, 2.5),
 (1.2777531299998797, 2.0),
 (1.3170777796132696, 1.5),
 (1.3552618543578767, 1.0),
 (1.3923991921155663, 0.5)]