# Exercises 4

## 1. Write a Python program that calculates how much money you can spend each day for lunch for the rest of the month based on today’s date and how much money you currently have in your lunch account. The program should ask you: (1) how much money you have in your account, (2) what today’s date is, and (3) how many days there are in the month. The program should return your daily allowance. The results of running your program should look like this:

#### How much money (in dollars) in your lunch account? 319
#### What day of the month is today? 21
#### How many days in this month? 30
#### You can spend 31.90 each day for the rest of the month.


## Extra: Create a dictionary (see §3.4) that stores the number of days in each month (forget about leap years) and have your program ask what month it is rather than the number of days in the month.


In [41]:
import numpy as np

lunch_account = float(input("How much money (in dollars) in your lunch account?"))
day_month     = float(input("What day of the month is today?"))
days_month    = float(input("How many days in this month?"))


How much money (in dollars) in your lunch account? 319
What day of the month is today? 21
How many days in this month? 30


In [42]:
days_left = lunch_account/((days_month - day_month) + 1)
print("You can spend ${0:.2f} each day for the rest of the month.".format(days_left))

You can spend $31.90 each day for the rest of the month.


In [43]:


year = {"January":31, "February":28, "March":21, "April":31, "May":31, "June":30, "July":30, "August":31, "September":30, "October":31, "November":30, "December":31}

lunch_account = float(input("How much money (in dollars) in your lunch account?: "))
month         = input("What month: ")
day_month     = float(input("What day of this month?: "))

days_left = lunch_account/ ((year[month]-day_month) + 1)
print("You can spend ${0:0.2f} each day for the rest of the month.".format(days_left))


How much money (in dollars) in your lunch account?:  319
What month: July
What day of this month?.21
You can spend $31.90 each day for the rest of the month.


## 2. From the IPython terminal, create the following three NumPy arrays:


#### a = array([1, 3, 5, 7])
#### b = array([8, 7, 5, 4])
#### c = array([0, 9,-6,-8])

## Now use the $\textit{zip}$ function to create a list d defined as. 

#### d = list(zip(a,b,c))

## What kind of object is each of the four elements of the list d? Convert d into a NumPy array and call that array e. Type e at the terminal prompt so that e is printed out on the IPython terminal. One of the elements of e is -8. Show how to address and print out just that element of e. Show how to address that same element of d. What kind of object is e[1]?


In [62]:
import numpy as np

a = [1, 3, 5, 7]
b = [8, 7, 5, 4]
c = [0, 9, -6, -8]

d = list(zip(a,b,c))
print(d)
print(type(d))
print(type(d[1]))
#It creates a list of tuples

e = np.array(d)
print(e)
print(type(e))
print(type(e[1]))
#It creates a Numpy array o Nympy array

[(1, 8, 0), (3, 7, 9), (5, 5, -6), (7, 4, -8)]
<class 'list'>
<class 'tuple'>
[[ 1  8  0]
 [ 3  7  9]
 [ 5  5 -6]
 [ 7  4 -8]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [67]:
print(e[3][2])
#Element -8
print(d[3][2])
#Element -8

print(e[1])

-8
-8
[3 7 9]


## 3. Create the following data file and then write a Python script to read it into three NumPy arrays with the variable names $f$, $a$, $da$ for the frequency, amplitude, and amplitude error.


In [4]:
import numpy as np

f, a, da = np.loadtxt("datafile.txt", skiprows=3, unpack=True)
print(f)
print(a)
print(da)

[ 0.75    1.7885  2.8269  3.8654  4.9038  5.9423  6.9808  8.0192  9.0577
 10.0962 11.1346 12.1731 13.2115 14.25  ]
[13.52 12.11 14.27 16.6  22.91 35.28 60.99 33.38 17.78 10.99  7.47  6.72
  4.4   4.07]
[0.32 0.92 0.73 2.06 1.75 0.91 0.99 0.36 2.32 0.21 0.48 0.51 0.58 0.63]


numpy.ndarray

# 4. Write a script to read the data from the previous problem into three NumPy arrays with the variable names f, a, da for the frequency, amplitude, and amplitude error and then, in the same script, write the data out to a data file, including the header, with the data displayed in three columns, just as it’s displayed in the problem above. It’s ok if the header lines begin with the # com- ment character. Your data file should have the extension .txt.

In [11]:
import numpy as np

f, a, da = np.loadtxt("datafile.txt", skiprows=3, unpack=True)


info = "Date: 2013-09-16"
info += "\nData taken by Liam and Selena"
info += "\nfrequency (Hz) amplitude (mm) amp error (mm)\n"

np.savetxt("newdatafile.txt", list(zip(f, a, da)), header = info, fmt = '%12.4f')


# 5. Write a script to read the data from the previous problem into three NumPy arrays with the variable names f, a, da for the frequency, amplitude, and amplitude error and then, in the same script, write the data out to a csv data file, without the header, to a data file with the data displayed in three columns preadsheet program (like MS Excel), try opening the file you have created with your Python script and verify that the arrays are displayed in three columns. 

# Note that your csv file should have the extension .csv.s. Use a single format specifier and set it to "%0.16e". If you have access the spreadsheet program (like MS Excel), try opening the file you have created with your Python script and verify that the arrays are displayed in three columns. Note that your csv file should have the extension .csv.

In [13]:
import numpy as np

f, a, da = np.loadtxt("datafile2.txt", skiprows=3, unpack=True)

np.savetxt("newdatafile2.csv", list(zip(f, a, da)), fmt="%0.16e", delimiter=',')